name: 'OpenApi Validator'
description: 'Validate an OpenApi specification with help of swagger-cli'
inputs:
  path:
    description: 'path of the api spec root file'
    default: 'api.yaml'
outputs:
  validate-result: 
    description: 'Result of validation process'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.validate-result }}
